from firebase import firebase

placeslist= {'London': ['Hampstead Heath, Park', 'Hyde Park, Park', "Regent's Park, Park", 'Mestizo Mexican Market, Furniture / Home Store'], 'Paris': ['Grand Bassin du Jardin du Luxembourg, Fountain', 'Parc des Buttes-Chaumont, Park', 'Hôtel de Crillon, Hotel', 'Jardin du Luxembourg, Garden'], 'New York': ['Central Park, Park', 'Brooklyn Bridge Park, Park', 'Hudson River Park, Park', 'Gantry Plaza State Park, State / Provincial Park']}

firebase = firebase.FirebaseApplication('https://smarttravelercompanion-default-rtdb.firebaseio.com/', None)  
for city in placeslist:
    data =  { 'cityname': city,
            'venue1': placeslist[city][0],
            'venue2': placeslist[city][1],
            'venue3': placeslist[city][2],
            'venue4': placeslist[city][3] }  
    result = firebase.post('smarttravelercompanion-default-rtdb/CityVenues',data)  
    print(result)




'''
{'London': ['Hampstead Heath, Park', 'Hyde Park, Park', "Regent's Park, Park", 'Mestizo Mexican Market, Furniture / Home 
Store'], 'Paris': ['Grand Bassin du Jardin du Luxembourg, Fountain', 'Parc des Buttes-Chaumont, Park', 'Hôtel de Crillon, Hotel', 'Jardin du Luxembourg, Garden'], 'New York': ['Central Park, Park', 'Brooklyn Bridge Park, Park', 'Hudson River 
Park, Park', 'Gantry Plaza State Park, State / Provincial Park'], 'Moscow': ['Чайхона #1, Middle Eastern Restaurant', 'Студия KateMagic, Salon / Barbershop', 'Торнадо, Sports Bar', 'Meshersky Park (Мещерский парк), Park'], 'Dubai': ['VOX Rooftop Cinema, Movie Theater', 'La Mer (لا مير), Neighborhood', 'The Beach, Beach', 'Fashion Avenue, Boutique'], 'Tokyo': ['Haginoyu (ひだまりの泉 萩の湯), Bath House', 'Blue Note Tokyo, Jazz Club', 'Koyama Shoten (小山商店), Liquor Store', 'Shinjuku Gyoen (新宿御苑), Garden'], 'Singapore': ['Gardens by the Bay, Garden', 'ATLAS Bar, Cocktail Bar', 'National Gal\xadlery Singa\xadpore, Art Gallery', 'Singapore Botanic Gardens, Botanical Garden'], 'Los Angeles': ['Griffith Park, Park', "Wally's, Wine Bar", 'Salt & Straw, Ice Cream Shop', 'Topanga State Park, State / Provincial Park'], 'Barcelona': ['Parc de la Ciutadella (Parque de la Ciudadela), Park', 'Torres Naixement, Historic Site', 'Motel One, Hotel', 'Búnkers del Carmel, Historic Site'], 'Madrid': ['Parque del Retiro, Park', 'Rosaleda del Retiro, Garden', 'La Primera, Restaurant', 'Teatro Nuevo Apolo, Theater'], 'Rome': ['Fontana dei Quattro Fiumi, Fountain', 'Pantheon, Monument / Landmark', 'Cupola di 
San Pietro, Scenic Lookout', 'Obelisco Flaminio, Monument / Landmark'], 'Doha': ['Novo Cinemas, Movie Theater', 'Aspire Park (حديقة اسباير), Park', 'Hakkasan, Chinese Restaurant', 'The St. Regis Doha, Resort'], 'Chicago': ['Millennium Park, Park', 'Grant Park, Park', 'The Art Institute of Chicago, Art Museum', "Binny's Beverage Depot, Liquor Store"], 'Abu Dhabi': ['The St. Regis Saadiyat Island Resort, Resort', 'Louvre Abu Dhabi Museum Shop, Souvenir Shop', 'Sheikh Zayed Grand Mosque (مسجد الشيخ زايد), Mosque', 'Umm Al Emarat Park (حديقة المشرف المركزية), Park'], 'San Francisco': ['Golden Gate Park, Park', 'Lands End Coastal Trail, Trail', 'Lands End Lookout, Scenic Lookout', 'Collis P. Huntington Park, Park'], 'Amsterdam': ['Vondelpark, Park', 'Margherita Tutta La Vita!, Pizza Place', 'Bistrot des Alpes, French Restaurant', 'Concerto 
Records, Record Shop'], 'St. Petersburg': ['Palace Square (Дворцовая площадь), Plaza', "Saint Isaac's Cathedral (Исаакиевский собор), Church", 'Saint Isaac’s Square (Исаакиевская площадь), Plaza', 'Soul Kitchen Hostel, Hostel'], 'Toronto': ['Port Union Waterfront Park, Park', 'The Old Spaghetti Factory, Italian Restaurant', 'Northern Belle, Cocktail Bar', 'High Park, Park'], 'Sydney': ['Bronte Coastal Walk, Trail', 'Sydney Opera House - Playhouse, Theater', 'Harris Farm Markets, 
Fruit & Vegetable Store', 'Queenscliff Beach, Beach'], 'Berlin': ['Großer Tiergarten, Park', 'Landwehrkanal, Canal', 'Tempelhofer Feld, Park', 'Treptower Park, Park'], 'Las Vegas': ['ARIA Pool & Cabanas, Hotel Pool', 'Red Rock Casino, Casino', 'Vdara Hotel & Spa, Hotel', 'Regal Red Rock 4DX & IMAX, Movie Theater'], 'Washington': ['Lincoln Memorial, Monument / Landmark', 'Georgetown Waterfront Park, Park', 'The John F. Kennedy Center for the Performing Arts, Performing Arts Venue', 'National Gallery of Art, Art Museum'], 'Istanbul': ['Aruna Cafe & Restaurant, Fish & Chips Shop', 'Süleymaniye Camii, 
Mosque', 'Fatih Camii, Mosque', 'Kahve Durağı, Coffee Shop'], 'Vienna': ['Schlosspark Schönbrunn, Park', 'Michaelerplatz, Plaza', 'Volksgarten, Park', 'Burggarten, Park'], 'Beijing': ['Rosewood Beijing (北京瑰丽酒店), Hotel', 'Din Tai Fung ( 
鼎泰丰), Dumpling Restaurant', 'The Great Wall at Juyong Pass (居庸关长城), Historic Site', 'Temple of Heaven (天坛), Temple'], 'Prague': ['Stromovka, Park', 'Havlíčkovy sady (Grébovka), Park', 'Mozzarellart, Cheese Shop', 'Vyhlídka Riegrovy 
sady, Scenic Lookout'], 'Milan': ['Piazza del Duomo, Plaza', 'Parco Sempione, Park', 'Excelsior Hotel Gallia, Hotel', 'Louis Vuitton, Boutique'], 'San Diego': ['Sunset Cliffs Natural Park, Park', 'Balboa Park, Park', 'Bobboi Natural Gelato, Ice Cream Shop', 'Torrey Pines State Natural Reserve, Nature Preserve'], 'Hong Kong': ['Morning Trail, The Peak (山頂晨運 
徑), Trail', 'Nan Lian Garden (南蓮園池), Garden', 'Broadway Cinematheque (百老匯電影中心), Multiplex', 'Flash (翻天覆地), Theme Park Ride / Attraction'], 'Melbourne': ['Melbourne Recital Centre, Performing Arts Venue', 'Boilermaker House, Whisky Bar', 'The Everleigh, Cocktail Bar', 'Royal Botanic Gardens, Botanical Garden'], 'Boston': ['Boston Public Garden, Garden', 'Boston Common, Park', 'The Esplanade, Park', 'Arnold Arboretum, Park'], 'Houston': ['Amorino, Ice Cream Shop', "Spec's Wines, Spirits & Finer Foods, Liquor Store", 'Buffalo Bayou Park, Park', 'Hermann Park, Park'], 'Dublin': ['The Spa At River Ridge, Salon / Barbershop', 'Amul India, Indian Restaurant', 'Pins Mechanical Company, Bar', 'Chick-fil-A, Fast Food Restaurant'], 'Miami': ['The Wynwood Walls, Public Art', 'Wynwood Art Walk, Art Gallery', 'Vizcaya Museum and Gardens, Museum', 'Publix, Grocery Store'], 'Zurich': ['Seebad Enge, Pool', 'Landiwiese, Park', 'Lindenhof, Pedestrian Plaza', 'Zürichhorn, Park'], 'Seattle': ['Green Lake Loop, Trail', 'Gas Works Park, Park', 'Elliott Bay Book Company, Bookstore', 'Alki Beach Path, Beach'], 'Budapest': ['Normafa, Scenic Lookout', 'Margitsziget, Island', 'Hotel Moments Budapest, Hotel', 'Diamante fagyizó, Ice Cream Shop'], 'Sao Paulo': ['Leroy Merlin Morumbi, Furniture / Home Store', 'Banca Villa Grano, Bookstore', 'Empório Moema, Bakery', 'Helena Bordon, Optical Shop'], 'Munich': ['Englischer Garten, Park', 'Eisbachwelle, Surf Spot', 'Isarufer an der Reichenbachbrücke, Beach', 'Olympiapark, Park'], 'Bangkok': ['Adhere the 13th Blues Bar, Jazz Club', 'ELF925, Factory', 'RBSC Fitness Club, Gym / Fitness Center', 'Books Kinokuniya (คิโนะคูนิยะ), Bookstore'],
 'Orlando': ['The Wizarding World of Harry Potter - Diagon Alley, Theme Park Ride / Attraction', 'Universal Orlando Resort, Theme Park', 'Universal Studios Florida, Theme Park', 'Mako, Theme Park Ride / Attraction'], 'Seoul': ['Namsan Walking Trail (남산산책로), Trail', 'Banpo Hangang Park (반포한강공원), Park', 'Gyeonghoeru (경회루), Historic Site', 'Olympic Park (올림픽공원), Park'], 'Atlanta': ['Piedmont Park, Park', 'Mercedes-Benz Stadium, Football Stadium', 'Atlanta BeltLine - Midtown, Trail', 'Chattahochee River National Recreation Area Palisades: Indian Trail, Trail'], 'Dallas': ['Klyde Warren Park, Park', 'Starbucks Reserve Bar, Coffee Shop', 'Deep Ellum Brewing Company, Brewery', 'iLoveKickboxing, Boxing Gym'], 'Frankfurt': ['Góc Phố, Vietnamese Restaurant', 'Kleinmarkthalle, Market', 'Kontrast, Furniture / Home Store', 'Zeit 
für Brot, Bakery'], 'Vancouver': ['Stanley Park, Park', 'Stanley Park English Bay Seawall, Trail', 'English Bay Beach, Beach', 'Coal Harbour Seawall, Waterfront'], 'Austin': ['Barton Creek Greenbelt, Trail', 'Austin Bouldering Project, Climbing Gym', 'Zilker Park, Park', 'Lady Bird Lake Trail, Trail'], 'Montreal': ['Parc du Mont-Royal, Park', 'Parc La Fontaine, Park', 'Marché Jean-Talon, Farmers Market', 'Vieux-Port de Montréal / Old Port of Montreal (Vieux-Port de Montréal), Historic Site'], 'Calgary': ["Prince's Island Park, Park", 'Spruce Meadows, Stables', 'Village Ice Cream, Ice Cream Shop', 'Monogram Coffee, Coffee Shop'], 'Delhi': ['Olive Bar & Kitchen, Italian Restaurant', 'Indian Accent, Indian Restaurant', 
'The Imperial, Hotel', 'The Big Chill Cafe, Restaurant'], 'Lisbon': ['Miradouro de Santa Luzia, Scenic Lookout', 'Miradouro do Castelo de São Jorge, Scenic Lookout', 'Miradouro da Senhora do Monte, Scenic Lookout', 'By the Wine - José Maria da Fonseca, Wine Bar'], 'Naples': ['Naples Beach, Beach', '5th Ave S Beach, Beach', 'Island Gypsy Cafe, Restaurant', 'Oakes Farms, Grocery Store'], 'Osaka': ['Umeda Mixed Juice (梅田ミックスジュース), Juice Bar', 'The Wizarding World of Harry 
Potter (ウィザーディング・ワールド・オブ・ハリー・ポッター), Theme Park Ride / Attraction', 'TAKAMURA Wine & Coffee Roasters, Wine Shop', 'The Flying Dinosaur (ザ・フライング・ダイナソー), Theme Park Ride / Attraction'], 'San Jose': ['Whole Foods Market, Grocery Store', 'San Jose Municipal Rose Garden, Garden', 'iLoveKickboxing, Boxing Gym', 'West Coast Cigars, Smoke Shop'], 'Riyadh': ['Diriyah Biennale (بينالي الدرعية), Art Gallery', 'Padel UP, Tennis Court', 'Easy Bakery (ايزي 
بيكري), Bakery', 'Plenty Sld’s (بلينتي سلدز), Salad Place'], 'Denver': ['Exclusive Martial Arts, Martial Arts School', 'Sushi Den, Sushi Restaurant', 'Washington Park, Park', 'Tattered Cover Bookstore, Bookstore'], 'Philadelphia': ['Café La Maude, Café', 'Barcelona Wine Bar, Tapas Restaurant', 'Washington Monument, Monument / Landmark', 'Elixr Coffee Roasters, 
Coffee Shop'], 'Tel Aviv': ['Teder.fm (תדר), Bar', 'Anita La Mamma Del Gelato (אניטה), Ice Cream Shop', 'Arte Glideria, Ice Cream Shop', 'Park HaYarkon (גני יהושוע / פארק הירקון), Park'], 'Copenhagen': ['Frederiksberg Have, Park', 'La Banchina, Restaurant', 'Koncerthuset, Concert Hall', 'Amager Strandpark, Beach'], 'Brussels': ['AB Ancienne Belgique, Music Venue', 'Grand Place / Grote Markt (Grote Markt), Plaza', 'Parc de Woluwepark (Woluwepark), Park', 'Ter Kamerenbos / Bois de 
la Cambre (Ter Kamerenbos), Forest'], 'Brisbane': ['Mount Coot-tha Lookout, Scenic Lookout', 'John Mills Himself, Coffee 
Shop', 'New Farm Park, Park', 'South Bank Parklands, Park'], 'Valencia': ['Jardines del Túria, Garden', 'Nozomi Sushi Bar, Japanese Restaurant', 'Casa Montaña, Spanish Restaurant', 'Mercat Central, Market'], 'Buenos Aires': ['Rapa Nui, Chocolate Shop', 'Rapa Nui, Ice Cream Shop', 'El Ateneo Grand Splendid, Bookstore', 'Alvear Icon, Hotel'], 'Taipei': ['Eslite Bookstore (誠品書店), Bookstore', 'Xiangshan Hiking Trail (象山登山步道), Trail', '天瓏電腦書局, Bookstore', 'Daan Forest 
Park (大安森林公園), Park'], 'Rio de Janeiro': ['Pedra do Arpoador, Scenic Lookout', 'Clube de Regatas do Flamengo, Sports Club', 'Morro da Urca, Mountain', 'Praia de Ipanema, Beach'], 'Portland': ['Washington Park, Park', 'Forest Park - Wildwood Trail, Trail', 'Mt. Tabor Park, Park', "Powell's City of Books, Bookstore"], 'Hamburg': ['Bohrkopf T.R.U.D.E., Historic Site', 'Isemarkt, Farmers Market', 'Planten un Blomen, Park', 'Savoy, Movie Theater'], 'Kuwait City': ['Al Shaheed Park (حديقة الشهيد), Park', 'Starbucks (ستاربكس), Coffee Shop', 'Grand Avenue (غراند أڤنيو), Shopping Mall', 'Bowling Centre, Bowling Alley'], 'Warsaw': ['Łazienki Królewskie, Park', 'Park Szczęśliwicki, Park', 'CH Arkadia, Shopping Mall', 'Palace On The Isle (Pałac Łazienkowski (Pałac Na Wyspie)), Palace'], 'Athens': ['Stavros Niarchos Park (Πάρκο Σταύρος Νιάρχος), Park', 'Herod Atticus Odeon (Ωδείο Ηρώδου Αττικού), Historic Site', 'Lighthouse (SNFCC), Art Gallery', 'Celia Kritharioti, Boutique'], 'Perth': ['Kings Park and Botanic Garden, Park', 'Cottesloe Beach, Beach', 'Leighton Beach, Beach', 'City Beach, Beach'], 'Helsinki': ['Riviera, Indie Movie Theater', 'Apéro, Wine Bar', 'Baskeri & Basso, Modern European Restaurant', 'Lilla Roberts, Hotel'], 'Minneapolis': ['South Lyndale Liquors, Liquor Store', 'Minnehaha Park, Park', 'Minnehaha Falls, Waterfall', 'Minneapolis Institute of Art, Art Museum'], 'Oslo': ['Åpent Bakeri Tranen, Bakery', 'Supreme Roastworks, Coffee Shop', 'Torggata Botaniske, Cocktail Bar', 'Le Benjamin Bar & Bistro, French Restaurant'], 'Shanghai': ['Pirates of the Caribbean Battle for the Sunken Treasure (加勒比海盗——沉落宝藏之战), Theme Park Ride / Attraction', 'TRON Lightcycle Power Run – Presented by Chevrolet (创极速光轮－雪佛兰呈献), Theme Park Ride / Attraction', 'Xuhui Riverside Park (徐汇滨江公园), Park', 'The Peninsula Shanghai, Hotel'], 'Phoenix': ['Wren House Brewing Company, Brewery', "Fry's Marketplace, Grocery Store", 'iLoveKickboxing - Glendale, Gym / Fitness Center', 'The Phoenician, Resort'], 'Auckland': ['Cornwall Park, Park', 'Mount Eden - Maungawhau, Mountain', 'Auckland Domain, Park', 'Auckland Zoo, Zoo'], 'New Orleans': ['Bacchanal Wine, Wine Bar', 'New Orleans City Park, Park', 'Audubon Park, Park', 'Cochon Butcher, Sandwich Place'], 'Jerusalem': ['Yad Vashem (יד ושם), History Museum', 'The Israel Museum (מוזיאון ישראל), Art Museum', 'Mahane Yehuda Market (שוק מחנה יהודה), Market', 'Notre Dame de Jerusalem, Hotel'], 'Muscat': ['The Chedi Hotel, Hotel', 'Shatti Al Qurum (شاطئ القرم), Beach', 'Al Bustan Palace, a Ritz-Carlton Hotel, Hotel', 'Royal Opera House (دار الأوبرا السلطانية), Opera House'], 
'Nashville': ["Jeni's Splendid Ice Creams, Ice Cream Shop", 'Belcourt Theatre, Indie Movie Theater', 'Ryman Auditorium, Music Venue', 'Shelby Bottoms Park & Nature Center, Park'], 'Stockholm': ['Klättercentret, Climbing Gym', 'Monteliusvägen, Trail', 'Pen Store, Arts & Crafts Store', 'Fotografiska, Art Museum'], 'Santiago': ['Parque Bicentenario, Park', 'CorpArtes, General Entertainment', 'Cerro San Cristóbal, Hill', 'Parque Araucano, Park'], 'Ottawa': ['Farm Boy, Grocery Store', "Major's Hill Park, Park", 'Moo Shu Ice Cream & Kitchen, Ice Cream Shop', 'La Bottega, Deli / Bodega'], 'Baltimore': ['Joseph Meyerhoff Symphony Hall, Concert Hall', 'Baltimore Museum of Art, Art Museum', 'The Wine Source, Wine Shop', 'Ceremony Coffee Roasters, Coffee Shop'], 'Edmonton': ['Remedy Cafe, Café', "Old Strathcona Farmers' Market, Farmers Market", 'Padmanadi, Vegetarian / Vegan Restaurant', 'Yokozuna, Japanese Restaurant'], 'Lyon': ["Parc de la Tête d'Or, Park", 'Le Musée, Lyonese Bouchon', 'Place des Jacobins, Plaza', 'Terre Adélice, Ice Cream Shop'], 'Marseille': ['Basilique Notre-Dame-de-la-Garde, Church', 'Calanque de Sormiou, Bay', "Café de l'Abbaye, Bar", 'Cathédrale Sainte-Marie-Majeure, Church'], 
'Adelaide': ['Grange Beach, Beach', 'Henley Beach South, Beach', 'Henley Beach, Beach', 'The Garden of Unearthly Delights, Performing Arts Venue'], 'Gothenburg': ['Slottsskogen, Park', 'Bhoga, Scandinavian Restaurant', 'Botaniska Trädgården, 
Botanical Garden', 'The Barn, Burger Joint'], 'Bilbao': ['Bihotz Café, Beer Bar', 'Puppy, Outdoor Sculpture', 'Morrocotuda Bar, Restaurant', 'Txakoli Simon, Spanish Restaurant'], 'Mexico City': ['Señor Taco, Mexican Restaurant', 'Centro Cultural Universitario, CCU, Cultura UNAM, Performing Arts Venue', 'Los Tulipanes, Bakery', 'Palacio de Bellas Artes, Opera House'], 'Salt Lake City': ['White Horse Spirits & Kitchen, Whisky Bar', 'Publik Coffee Roasters, Coffee Shop', "Valter's, 
Italian Restaurant", 'Liberty Park, Park'], 'Mumbai': ['Palladium, Shopping Mall', 'Taj Mahal Palace & Tower, Hotel', 'Prithvi Theatre, Theater', "McDonald's, Fast Food Restaurant"], 'Sacramento': ['Temple Coffee & Tea, Coffee Shop', 'The Sandwich Spot, Sandwich Place', 'The Kitchen, New American Restaurant', 'Crocker Art Museum, Art Museum'], 'San Antonio': ['Hotel EMMA, Hotel', 'The Shops at La Cantera, Shopping Mall', 'Total Wine & More, Wine Shop', 'iLoveKickboxing - Stone Oak, TX, Gym'], 'Tucson': ['Mount Lemmon, Mountain', 'Gene C Reid Park, Park', "Trader Joe's, Grocery Store", 'JW Marriott 
Tucson Starr Pass Resort & Spa, Hotel'], 'Seville': ['Plaza de España, Plaza', 'Cathedral of Seville (Catedral de Sevilla), Church', 'La Giralda, Monument / Landmark', 'Real Alcázar de Sevilla, Palace'], 'Charlotte': ['Salud Beer Shop, Bar', 
'Freedom Park, Park', 'McDowell Nature Center and Preserve, Trail', 'Fury 325, Theme Park Ride / Attraction'], 'Nanjing': ['Librairie Avant-Garde (先锋书店), Bookstore', 'Nanjing University (南京大学), University', 'Hilton Nanjing Riverside (南京世茂滨江希尔顿酒店), Hotel', 'Xuanwu Lake Park (玄武湖公园), Park']}
'''